import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createInkStore, inkDate } from '../local/ink-store.mjs';
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'material-ink-test-'));
const file = path.join(directory, 'ink.json');
try {
  let store = createInkStore(file);
  const base = store.snapshot();
  assert.equal(base.stockTotal, 137160);
  assert.equal(base.products[0].onHand, 2);
  assert.equal(inkDate('2026-09-30').year, 2569);
  assert.equal(inkDate('2026-10-01').year, 2570);
  assert.throws(() => inkDate('2026-02-30'));
  const product = store.commit({ operationId: 'product-test-00001', revision: 0, name: 'หมึกทดสอบ' }, 'PRODUCT');
  assert.equal(product.state.products.at(-1).onHand, 0);
  const receipt = { operationId: 'purchase-test-0001', revision: 1, date: '2026-08-03', baselineDate: '2026-08-03', confirmBaseline: true, lines: [{ productId: product.id, quantity: 10, unitPrice: 12.5 }, { productId: base.products[0].id, quantity: 2, unitPrice: 2400 }] };
  assert.throws(() => store.commit({ ...receipt, confirmBaseline: false }, 'PURCHASE'));
  const purchase = store.commit(receipt, 'PURCHASE');
  assert.equal(purchase.id, 'INK-PUR-2569-00001');
  assert.equal(purchase.state.products.at(-1).onHand, 10);
  assert.equal(purchase.state.products[0].onHand, 4);
  assert.equal(purchase.state.groups.at(-1).total, 4925);
  assert.equal(store.commit(receipt, 'PURCHASE').state.revision, 2);
  store = createInkStore(file);
  assert.equal(store.commit(receipt, 'PURCHASE').state.revision, 2, 'retry after restart does not double-post');
  assert.throws(() => store.commit({ ...receipt, date: '2026-08-04' }, 'PURCHASE'));
  assert.throws(() => store.commit({ ...receipt, operationId: 'stale-test-00001' }, 'PURCHASE'));
  const issue = { operationId: 'withdraw-test-0001', revision: 2, date: '2026-08-04', department: 'วิชาการ', lines: [{ productId: product.id, quantity: 3 }] };
  const withdrawal = store.commit(issue, 'WITHDRAWAL');
  assert.equal(withdrawal.state.products.at(-1).onHand, 7);
  assert.equal(withdrawal.state.withdrawals.at(-1).cells[3], 3);
  const before = fs.readFileSync(file, 'utf8');
  assert.throws(() => store.commit({ ...issue, operationId: 'oversell-test-0001', revision: 3, lines: [{ productId: base.products[0].id, quantity: 1 }, { productId: product.id, quantity: 99 }] }, 'WITHDRAWAL'));
  assert.equal(fs.readFileSync(file, 'utf8'), before, 'failed multiline transaction is atomic');
  assert.throws(() => store.commit({ ...receipt, operationId: 'negative-test-0001', revision: 3, date: '2026-08-05', lines: [{ productId: product.id, quantity: 1, unitPrice: -1 }] }, 'PURCHASE'));
  assert.throws(() => store.commit({ ...receipt, operationId: 'backdate-test-0001', revision: 3 }, 'PURCHASE'));
  assert.throws(() => store.commit({ operationId: 'duplicate-test-0001', revision: 3, name: ' หมึกทดสอบ ' }, 'PRODUCT'));
  assert.throws(() => store.commit({ ...issue, operationId: 'duplicate-lines-0001', revision: 3, lines: [issue.lines[0], issue.lines[0]] }, 'WITHDRAWAL'));
  assert.equal(createInkStore(file).snapshot().products.at(-1).onHand, 7);
  assert.equal(store.backup().transactions.length, 2);
  assert.ok(fs.existsSync(`${file}.bak`));
  let sequence = 0;
  const change = (key, action, values = {}) => store.commit({ operationId: `change-test-${String(++sequence).padStart(5, '0')}`, revision: store.snapshot().revision, key, action, reason: 'แก้ข้อมูลผิด', ...values }, 'CHANGE');
  const originalTotal = store.snapshot().stockTotal;
  const sourcePurchase = store.snapshot().groups[0].rows[0];
  change(sourcePurchase.editKey, 'UPDATE', { name: 'แก้ชื่อเดิม', quantity: 2, unitPrice: 100 });
  assert.equal(store.snapshot().groups[0].rows[0].cells[4], 200);
  assert.equal(store.snapshot().stockTotal, originalTotal, 'source correction does not double-count stock');
  change(sourcePurchase.editKey, 'DELETE');
  assert.equal(store.snapshot().groups[0].rows.length, 7);
  const sourceWithdrawal = store.snapshot().withdrawals[0];
  change(sourceWithdrawal.editKey, 'UPDATE', { name: 'แก้เบิกเก่า', quantity: 2, department: 'บริหาร', date: '2025-03-01' });
  assert.equal(store.snapshot().withdrawals[0].cells[0], '01/03/2568');
  change(sourceWithdrawal.editKey, 'DELETE');
  assert.equal(store.snapshot().withdrawals.length, 36);
  change(`transaction:${withdrawal.id}`, 'UPDATE', { date: issue.date, department: 'แก้ฝ่าย', lines: [{ productId: product.id, quantity: 2 }] });
  assert.equal(store.snapshot().products.at(-1).onHand, 8);
  assert.throws(() => change(`transaction:${purchase.id}`, 'DELETE'), /ติดลบ/);
  change(`transaction:${withdrawal.id}`, 'DELETE');
  assert.equal(store.snapshot().products.at(-1).onHand, 10);
  change(`transaction:${purchase.id}`, 'UPDATE', { date: receipt.date, lines: [{ productId: product.id, quantity: 12, unitPrice: 15 }] });
  assert.equal(store.snapshot().products.at(-1).onHand, 12);
  change(`transaction:${purchase.id}`, 'DELETE');
  assert.equal(store.snapshot().products.at(-1).onHand, 0);
  change(`stock:${product.id}`, 'UPDATE', { name: 'ชื่อใหม่', quantity: 5, unitPrice: 30 });
  assert.equal(store.snapshot().products.at(-1).onHand, 5);
  assert.equal(store.snapshot().products.at(-1).unitPrice, 30);
  assert.throws(() => change(`stock:${product.id}`, 'DELETE'), /เป็น 0/);
  change(`stock:${product.id}`, 'UPDATE', { name: 'ชื่อใหม่', quantity: 0, unitPrice: 30 });
  change(`stock:${product.id}`, 'DELETE');
  assert.equal(store.snapshot().products.length, 14);
  const notes = store.commit({ operationId: 'notes-test-000001', revision: store.snapshot().revision, sections: [
    { id: 'INK-NOTE-0001', title: 'เหตุผลที่ปรับปรุงแล้ว', reasons: ['เหตุผลข้อแรก', 'เหตุผลข้อสอง'] },
    { title: 'หัวข้อเพิ่มเติม', reasons: ['รายละเอียดเพิ่มเติม'] },
  ] }, 'NOTES');
  assert.equal(notes.id, 'INK-NOTES');
  assert.equal(notes.state.purchaseNoteSections.length, 2);
  assert.equal(notes.state.purchaseNoteSections[1].title, 'หัวข้อเพิ่มเติม');
  assert.throws(() => store.commit({ operationId: 'notes-invalid-0001', revision: store.snapshot().revision, sections: [{ title: 'ไม่มีเหตุผล', reasons: [] }] }, 'NOTES'), /เหตุผล/);
  assert.ok(store.snapshot().audit.some(entry => entry.before && entry.after && entry.action === 'DELETE'));
  assert.equal(createInkStore(file).snapshot().purchaseNoteSections[0].title, 'เหตุผลที่ปรับปรุงแล้ว');
  assert.equal(createInkStore(file).snapshot().audit.length, store.snapshot().audit.length);
  const inlineFile = path.join(directory, 'inline.json');
  const inline = createInkStore(inlineFile);
  const inlineReceipt = { operationId: 'inline-purchase-0001', revision: 0, date: '2026-08-03', baselineDate: '2026-08-03', confirmBaseline: true, lines: [{ newProductName: 'รุ่นใหม่จากซื้อเข้า', quantity: 4, unitPrice: 125 }, { productId: base.products[0].id, quantity: 2, unitPrice: 100 }] };
  const savedInline = inline.commit(inlineReceipt, 'PURCHASE');
  assert.equal(savedInline.state.products.at(-1).onHand, 4);
  assert.equal(savedInline.state.groups.at(-1).total, 700);
  assert.equal(inline.commit(inlineReceipt, 'PURCHASE').id, savedInline.id);
  assert.equal(inline.snapshot().products.length, 15, 'retry does not create another model');
  const inlineBefore = fs.readFileSync(inlineFile, 'utf8');
  const badReceipt = { ...inlineReceipt, operationId: 'inline-invalid-0001', revision: 1, lines: [{ newProductName: 'ห้ามเหลือรุ่นนี้เมื่อบันทึกไม่ผ่าน', quantity: 1, unitPrice: 10 }, { productId: base.products[0].id, quantity: -1, unitPrice: 10 }] };
  assert.throws(() => inline.commit(badReceipt, 'PURCHASE'));
  assert.equal(fs.readFileSync(inlineFile, 'utf8'), inlineBefore);
  assert.throws(() => inline.commit({ ...badReceipt, lines: [{ newProductName: ' รุ่นใหม่จากซื้อเข้า ', quantity: 1, unitPrice: 10 }] }, 'PURCHASE'), /มีชื่อหมึก/);
  assert.throws(() => inline.commit({ ...badReceipt, lines: [{ newProductName: 'same', quantity: 1, unitPrice: 10 }, { newProductName: ' SAME ', quantity: 1, unitPrice: 10 }] }, 'PURCHASE'), /มีชื่อหมึก/);
  assert.throws(() => inline.commit({ ...badReceipt, department: 'ทดสอบ', lines: [{ newProductName: 'ห้ามสร้างจากการเบิก', quantity: 1 }] }, 'WITHDRAWAL'));
  let deleteSerial = 0;
  const removeWithoutReason = key => inline.commit({ operationId: `inline-delete-${++deleteSerial}`, revision: inline.snapshot().revision, key, action: 'DELETE' }, 'CHANGE');
  removeWithoutReason(`transaction:${savedInline.id}`);
  assert.equal(inline.snapshot().products.at(-1).onHand, 0);
  removeWithoutReason(`stock:${savedInline.state.products.at(-1).id}`);
  removeWithoutReason(inline.snapshot().groups[0].rows[0].editKey);
  removeWithoutReason(inline.snapshot().withdrawals[0].editKey);
  assert.equal(inline.snapshot().products.length, 14);
  assert.equal(inline.snapshot().audit.filter(item => item.action === 'DELETE' && item.reason === '').length, 4);
  assert.equal(createInkStore(inlineFile).snapshot().revision, inline.snapshot().revision);
  const readOnly = createInkStore(file, undefined, { role: 'user' });
  assert.equal(readOnly.snapshot().canManage, false);
  assert.throws(() => readOnly.commit({ operationId: 'role-test-00001', revision: store.snapshot().revision, name: 'forbidden' }, 'PRODUCT'), /ผู้ดูแล/);
  process.env.INK_DATA_PATH = path.join(directory, 'http-ink.json');
  const { server } = await import('../local/server.mjs');
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const baseUrl = `http://127.0.0.1:${server.address().port}`;
  try {
    assert.equal((await (await fetch(`${baseUrl}/api/ink/state`)).json()).data.products.length, 14);
    const payload = { operationId: 'http-product-0001', revision: 0, name: 'HTTP test ink' };
    const denied = await fetch(`${baseUrl}/api/ink/products`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://untrusted.example' }, body: JSON.stringify(payload) });
    assert.equal(denied.status, 403);
    const accepted = await fetch(`${baseUrl}/api/ink/products`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: baseUrl }, body: JSON.stringify(payload) });
    assert.equal(accepted.status, 200);
    assert.equal((await accepted.json()).data.state.products.length, 15);
    const notesPayload = { operationId: 'http-notes-000001', revision: 1, sections: [{ title: 'หัวข้อจาก API', reasons: ['เหตุผลจาก API'] }] };
    const savedNotes = await fetch(`${baseUrl}/api/ink/notes`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: baseUrl }, body: JSON.stringify(notesPayload) });
    assert.equal(savedNotes.status, 200);
    assert.equal((await savedNotes.json()).data.state.purchaseNoteSections[0].title, 'หัวข้อจาก API');
    const backup = await fetch(`${baseUrl}/api/ink/backup`);
    assert.match(backup.headers.get('content-disposition'), /attachment/);
    assert.equal((await backup.json()).products.length, 15);
  } finally { await new Promise(resolve => server.close(resolve)); }
  console.log('PASS ink persistence: products, multiline purchases, withdrawals, baseline, fiscal dates, duplicate retries, concurrency, atomic validation, backups and restart.');
} finally {
  fs.rmSync(directory, { recursive: true, force: true });
}
